scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'hyper-node-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'hyper-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8899']
  - job_name: 'polygon-heimdall'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:26660']
  - job_name: 'polygon-bor'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
    - targets: ['localhost:7071']
